language: cpp
compiler:
    - gcc
    - clang
env:
    - CONFIG=debug QT=qt5 QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
    - CONFIG=release QT=qt5 QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
    - CONFIG=debug QT=qt4 QMAKE=qmake
    - CONFIG=release QT=qt4 QMAKE=qmake
sudo: false
addons:
  apt:
    sources:
        - ubuntu-sdk-team
    packages:
        - build-essential
        - libqt4-dev
        - zlib1g-dev
        - qt4-dev-tools
        - libqtwebkit-dev
        - qtdeclarative5-dev
        - time

script: time sh -c "mkdir _build; cd _build; $QMAKE QMAKE_CXX=$CXX CONFIG+=$CONFIG ../QtSnap.pro && make"
